//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP_123_Assignment06_300813612_JihoYoo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMP_123_Assignment06_300813612_JihoYoo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string CalculateButtonEnglish {
            get {
                return ResourceManager.GetString("CalculateButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer.
        /// </summary>
        internal static string CalculateButtonFrench {
            get {
                return ResourceManager.GetString("CalculateButtonFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID:.
        /// </summary>
        internal static string EmployeeIDLabelEnglish {
            get {
                return ResourceManager.GetString("EmployeeIDLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID:.
        /// </summary>
        internal static string EmployeeIDLabelFrench {
            get {
                return ResourceManager.GetString("EmployeeIDLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s name:.
        /// </summary>
        internal static string EmployeeNameLabelEnglish {
            get {
                return ResourceManager.GetString("EmployeeNameLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;employé:.
        /// </summary>
        internal static string EmployeeNameLabelFrench {
            get {
                return ResourceManager.GetString("EmployeeNameLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishRadioButtonEnglish {
            get {
                return ResourceManager.GetString("EnglishRadioButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        internal static string EnglishRadioButtonFrench {
            get {
                return ResourceManager.GetString("EnglishRadioButtonFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string FrenchRadioButtonEnglish {
            get {
                return ResourceManager.GetString("FrenchRadioButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string FrenchRadioButtonFrench {
            get {
                return ResourceManager.GetString("FrenchRadioButtonFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LanguagesGroupBoxEnglish {
            get {
                return ResourceManager.GetString("LanguagesGroupBoxEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langues.
        /// </summary>
        internal static string LanguagesGroupBoxFrench {
            get {
                return ResourceManager.GetString("LanguagesGroupBoxFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next .
        /// </summary>
        internal static string NextButtonEnglish {
            get {
                return ResourceManager.GetString("NextButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        internal static string NextButtonFrench {
            get {
                return ResourceManager.GetString("NextButtonFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string PrintButtonEnglish {
            get {
                return ResourceManager.GetString("PrintButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        internal static string PrintButtonFrench {
            get {
                return ResourceManager.GetString("PrintButtonFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Bonus.
        /// </summary>
        internal static string SaleBonusFormEnglish {
            get {
                return ResourceManager.GetString("SaleBonusFormEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vente Bonus.
        /// </summary>
        internal static string SaleBonusFormFrench {
            get {
                return ResourceManager.GetString("SaleBonusFormFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Bonus.
        /// </summary>
        internal static string SalesBonusActiveFormEnglish {
            get {
                return ResourceManager.GetString("SalesBonusActiveFormEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vente Bonus.
        /// </summary>
        internal static string SalesBonusActiveFormFrench {
            get {
                return ResourceManager.GetString("SalesBonusActiveFormFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Bonus:.
        /// </summary>
        internal static string SalesBonusLabelEnglish {
            get {
                return ResourceManager.GetString("SalesBonusLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventes Bonus:.
        /// </summary>
        internal static string SalesBonusLabelFrench {
            get {
                return ResourceManager.GetString("SalesBonusLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours Worked:.
        /// </summary>
        internal static string TotalHoursWorkedLabelEnglish {
            get {
                return ResourceManager.GetString("TotalHoursWorkedLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total des heures travaillées:.
        /// </summary>
        internal static string TotalHoursWorkedLabelFrench {
            get {
                return ResourceManager.GetString("TotalHoursWorkedLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Monthly Sales:.
        /// </summary>
        internal static string TotalMonthlySalesLabelEnglish {
            get {
                return ResourceManager.GetString("TotalMonthlySalesLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les ventes mensuelles totales:.
        /// </summary>
        internal static string TotalMonthlySalesLabelFrench {
            get {
                return ResourceManager.GetString("TotalMonthlySalesLabelFrench", resourceCulture);
            }
        }
    }
}
